

---
deployment:
 tasks:
 - export DEPLOYPATH=/home/pumpkinp/public_html/
 - export REPOPATH=/home/pumpkinp/repositories/pumpkin-plus-website
 - /bin/cp -R ${REPOPATH}/build/* $DEPLOYPATH
 - /bin/cp -R ${REPOPATH}/public/* $DEPLOYPATH
 - /bin/cp ${REPOPATH}/.htaccess $DEPLOYPATH 2>/dev/null || true
branches:
 - main